# Generated by Django 3.2 on 2021-04-17 10:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='detail',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='plans',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='plans',
            name='time_todo',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 17, 10, 22, 3, 131242)),
        ),
    ]
