# Generated by Django 3.2 on 2021-04-19 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210417_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plans',
            name='time_todo',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 8, 41, 7, 284081)),
        ),
    ]
