# Generated by Django 3.2 on 2021-04-19 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210419_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='detail',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='plans',
            name='time_todo',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 19, 16, 9, 5, 810263)),
        ),
    ]
