# Generated by Django 3.2 on 2021-04-27 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210419_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('detail', models.TextField()),
                ('time_todo', models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 4, 37, 14, 643873))),
                ('completed', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
